# Note: semgrep on its own does not prove the code to be safe,
#       as all rules can be bypassed when a malicious attacker desires to do so.
#       It is meant to enforce cleaner and more readable and code that is easy to reason about.

rules:
    -   id: js-no-eval
        message: "Do not use eval."
        severity: ERROR
        languages: [ javascript ]
        pattern: eval(...)

    -   id: js-no-new-function
        message: "Do not use new Function."
        severity: ERROR
        languages: [ javascript ]
        pattern: new Function(...)

    -   id: js-no-document-cookie
        message: "Do not access document.cookie."
        severity: ERROR
        languages: [ javascript ]
        pattern: document.cookie

    -   id: js-no-sendbeacon
        message: "Do not use navigator.sendBeacon."
        severity: ERROR
        languages: [ javascript ]
        pattern: navigator.sendBeacon(...)

    -   id: js-no-websocket
        message: "Do not use WebSockets."
        severity: ERROR
        languages: [ javascript ]
        pattern: new WebSocket(...)

    -   id: js-no-cross-window-postmessage
        message: "Do not use window.postMessage."
        severity: ERROR
        languages: [ javascript ]
        pattern: window.postMessage(...)

    -   id: js-fetch-non-whitelisted-domain
        message: "fetch() URL should be YouTube only."
        severity: ERROR
        languages: [ javascript ]
        patterns:
            -   pattern: fetch($URL, ...)
            -   metavariable-regex:
                    metavariable: $URL
                    regex: ()['"`](?!.*youtube\.com).*['"` ]()
    -   id: js-no-location-rewrite-to-non-youtube
        message: "Do not change window.location to non-YouTube domains."
        severity: ERROR
        languages: [ javascript ]
        patterns:
            -   pattern: window.location = $URL
            -   pattern: location = $URL
            -   metavariable-regex:
                    metavariable: $URL
                    regex: ()['"`](?!.*youtube\.com).*['"` ]()

    -   id: js-no-location-href-rewrite-to-non-youtube
        message: "Do not change window.location.href to non-YouTube domains."
        severity: ERROR
        languages: [ javascript ]
        patterns:
            -   pattern: window.location.href = $URL
            -   pattern: location.href = $URL
            -   metavariable-regex:
                    metavariable: $URL
                    regex: ()['"`](?!.*youtube\.com).*['"` ]()

    -   id: js-no-open-non-youtube
        message: "Do not use window.open to non-YouTube domains."
        severity: ERROR
        languages: [ javascript ]
        patterns:
            -   pattern: window.open($URL, ...)
            -   pattern: open($URL, ...)
            -   metavariable-regex:
                    metavariable: $URL
                    regex: ()['"`](?!.*youtube\.com).*['"` ]()
